language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lehoan0212/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lehoan0212/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  environment: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-570317453708"
  path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
