language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lehoan0212/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lehoan0212/docker-react npm run test -- --coverage
